### ISSUE TITLE
Unexpected trigger at the beginning of line

### ISSUE THREAD

**Issue by failable** [awth13/org-appear#10]
<img width="333" alt="Screen Shot 2021-03-13 at 2 12 11 PM" src="https://user-images.githubusercontent.com/5475262/111021272-1f9d3a00-8406-11eb-95ef-c7903048e059.png">

When the cursor is placed in the beginning of line, `org-appear` is triggered to display markers of previous line.

**Comment by awth13** [comment]
Thank you for posting the issue, @liebkne!

Before you start writing something after a headline, `org-element` (which we use to detect elements) thinks that the next line is part of the last element in the headline. I'm trying to find out why it does that with headlines only -- I don't really like the idea of doing boundary checks after each command to fix this.

**Comment by awth13** [comment]
This issue is now [resolved](https://github.com/awth13/org-appear/commit/f0e9d53a29443c783135ce4f6977af625b991a9a) so I am closing it. Thank you again for posting it here!
