### ISSUE TITLE
Feature request? Add support for hiding properties like #+title and #+author

### ISSUE THREAD

**Issue by powerverwirrt** [awth13/org-appear#22]
Hiya, thanks for this awesome little package! Makes my notes much tidier and nicer to look at!

I was wondering whether org-appear could support hiding/unhiding properties that are set at the beginning of the file, like #+TITLE and #+AUTHOR.

Since I don't know a lot of Elisp, I'm not sure if I could build this myself and open a PR... Are those properties accessible via the org-element API?

Kind regards
Luke

**Comment by awth13** [comment]
Hey, @powerverwirrt!

Thanks for your interest! There is an `org-hidden-keywords` custom variable that you can set to hide, e.g., the `#+TITLE` part of a property. If you do that, only the value of `#+TITLE` will be visible. I don't think that Org supports hiding both the keyword and its value.

From a brief experiment, Org hides the`#+TITLE` part using the same mechanism it uses to hide emphasis markers. Also, `org-element` can detect keywords in a document. This means that it should be possible to make `org-appear` *unhide* the `#+TITLE` part in a document where it is hidden (and hide it again once the cursor leaves).

If you want to add this functionality yourself, I suggest looking at commits by @SPFabGerman, e.g., [this one](https://github.com/awth13/org-appear/commit/1e20d00173fbe94b14f743de592fa5f609d617d2). They added a bunch of new elements to `org-appear` and you can learn how to do this from their commits.

**Comment by SPFabGerman** [comment]
Huh, I didn't even know that org-mode had support for hiding keywords. You learn something new every day, I guess.
So yeah I implemented a quick PR, that implements keyword-toggling and I think it already works decently well.

**Comment by powerverwirrt** [comment]
Thanks so much to both of you! It's amazing that you got back to me so quickly! I'll test the code and report back/close the issue. :+1:

**Comment by awth13** [comment]
@SPFabGerman to the rescue :D

> Huh, I didn't even know that org-mode had support for hiding keywords.

Me too. Thanks to @powerverwirrt for suggesting it!

**Comment by powerverwirrt** [comment]
Tested it yesterday and today and it works nicely! Thanks @SPFabGerman! This community is awesome. Should this stay open until the PR is merged?

**Comment by awth13** [comment]
Thanks again, @powerverwirrt!

The issue has been closed automatically since the PR was marked as closing it.
