### ISSUE TITLE
org-appear cuts off parts of links without brackets

### ISSUE THREAD

**Issue by japhir** [awth13/org-appear#24]
When I have a plain url in an org file, it tries to format it nicely but ends up cutting off some parts:
`https://emacs.org` turns into `tps://emacs.o`.
If I turn off org-appear-mode it looks normal.

**Comment by japhir** [comment]
Notice that the [org manual](https://orgmode.org/manual/Link-Format.html#Link-Format) says that "Org recognizes plain URIs, possibly wrapped within angle brackets" so plain URL's should be acceptable org syntax :)

**Comment by awth13** [comment]
Thanks, @japhir! Can't believe I missed that!

[Fixed](https://github.com/awth13/org-appear/commit/36c02661b57e94d1c8b66c6c0642e899b7539680).
