### ISSUE TITLE
org appear wrongfully hides org-ref links with pre- and postscripts

### ISSUE THREAD

**Issue by japhir** [awth13/org-appear#25]
[org-ref](https://github.com/jkitchin/org-ref) has a way to write prefixes and postfixes by using the link syntax, e.g. `[[parencite:Einstein1960][e.g.::]]` or `[[parencite:Einstein1960][::page 15]]`.

These now get previewed as `e.g.::` in stead of remaining a differently formatted (colour) org-ref entry that still displays the full link. Any way to turn this particular link type folding off?

**Comment by japhir** [comment]
note that parencite can be `cite`, `parencite` `textcite` and many more

**Comment by awth13** [comment]
Thanks again :)

Fixed in c9275182c12e924136a0f4b7a085579e7a77a3b0. `org-appear` now ignores all link types that contain "cite" or "Cite". That should cover all org-ref link variations except `bibentry` (`bibentry` is a plain link and is ignored by another condition).

**Comment by japhir** [comment]
Great! Seems to work!
