### ISSUE TITLE
compatibility with org-use-sub-superscripts

### ISSUE THREAD

**Issue by ilupin** [awth13/org-appear#30]
When `org-use-sub-superscripts` is `{}` or nil, org-mode displays `a_{b}` as a<sub>b</sub> and ignores a_b. 

If org-appear is enabled with `(setq org-appear-autosubmarkers t)`, a_b is displayed as ab, where the character `_` is invisible.

**Comment by awth13** [comment]
Thank you for opening the issue, @ilupin! I didn't know that there is an extra customisation variable for sub/superscripts beyond `org-pretty-entities`.

The issue should now be fixed.
