### ISSUE TITLE
Feature request: keybinding/function to trigger appearing without an edit

### ISSUE THREAD

**Issue by Kazark** [awth13/org-appear#37]
I have been trying out the new only appear on change option, and overall I really like it. I started using `org-appear` originally because I was so tired of globally toggling things on and off just to edit links. However, with time (and some links with longer targets) the jerkiness of having them open whenever I navigated over them began to wear on me. I checked here to see my options, and found the new behavior had just been implemented. I immediately switched to it, and am much happier.

There is one thing I can think of that would improve my experience with it. When I go to edit a link, it's not always because I want to edit the link description. Sometimes I want to edit the target---say, when I yanked the link from another file and need to add a `../` to the filepath, or the like. Right now I have to trigger this by editing the description, then undoing my edit, then editing the target. This is okay, but it is a little clunky.

It would be nice to have a function to bind that would trigger this at a keystroke. Perhaps there is already such a function, but it looked to me like all the functions were using the convention for private (`--` after the namespace).

I am an Evil user, so I would actually love to be able to hook this into the Evil system so that when I typed `i` or `a` on a link from normal mode, the link would open. It's kind of cool to think what you could do with Evil mode integration here, since the very modality of Evil helps with the idea of only opening on edit. Still, I can imagine that you may not want to get yourself into something as specific as Evil. Presumably if there was a function I could add to an Evil hook, I could achieve this easily enough.

Thoughts?

**Comment by SPFabGerman** [comment]
Hi, I haven't tested it, but just calling the function `org-appear--after-change` in a hook or with a keybinding should do the trick.
But I agree, having a public function for that would be good.
Also an option to only show the markers manually is probably a good idea.
(I also like your idea of integrating that with evil. Maybe I will work on that, when I have time.)

**Comment by awth13** [comment]
Hi, @Kazark!

I am an Evil user as well, and integration with the modal system is something I thought of immediately when @Yevgnen suggested the `on-change` feature. Unfortunately, I caught the Omicron variant right after that and couldn't dedicate my time to implementing this.

A function that binds to `evil-insert-state-entry-hook` is a very good idea! I think we can make it a third option for `org-appear-trigger`, something like `on-hook`, and let the user decide when `org-appear` triggers with that option. I will work on that as soon as I can, unless, of course, @SPFabGerman implements it first.

**Comment by Kazark** [comment]
Thanks to both of you! Let me know if I can help. I'm not familiar with this codebase, or the internals of Evil, or certain parts of Emacs; but I am a relatively advanced user of Emacs Lisp, as far as that goes.

**Comment by awth13** [comment]
>  I'm not familiar with this codebase, or the internals of Evil, or certain parts of Emacs; but I am a relatively advanced user of Emacs Lisp, as far as that goes.

I cannot say that I am particularly familiar with the parts of Emacs we're working with here -- if anything, my work on `org-appear` only left me more confused about certain parts, especially the `jit-lock-mode`. Regarding potential help, I must say I would very much welcome an experienced eye going over the code and seeing if any parts of it look bad from the best practices perspective. This package was the first "serious" Elisp code that I wrote in my life and I am learning on the go.

**Comment by awth13** [comment]
With the work already done by @SPFabGerman for the `on-change` functionality, implementing a manual trigger mode has been pretty straightforward. The new functionality can be tested in the [feature/manual-trigger](https://github.com/awth13/org-appear/tree/feature/manual-trigger) branch using these settings:

```
(setq org-appear-trigger 'manual)
(add-hook 'evil-insert-state-entry-hook #'org-appear-manual-start nil t)
(add-hook 'evil-insert-state-exit-hook #'org-appear-manual-stop nil t)
```

@Kazark, does this align with your expectations of the new functionality?

I think not adding the above two hooks within `org-appear` and letting the user add them as they wish is a better solution that still allows for an easy integration with Evil. My only doubt is whether `org-appear-manual-start` and `org-appear-manual-stop` should be made interactive or not.

**Comment by Kazark** [comment]
@awth13 it's possible I'll find something after using it for a while, but after an initial test I can only say :tada: **FANTASTIC** :tada:.

**Comment by Kazark** [comment]
@awth13 as far as leaving the user to configure the hooks, I do think that makes sense. I have prepped a commit for Spacemacs which, if you have appear enabled and set to trigger manually, and you are using modal editing, will set these hooks up for Org buffers. Once your changes are available in the package repository, I will submit this as a PR to Spacemacs.

**Comment by awth13** [comment]
Great! I enjoy this feature a lot as well so thank you for the fantastic suggestion, @Kazark.

> Once your changes are available in the package repository

They are now :)

**Comment by Kazark** [comment]
@awth13 is publishing to Melpa a manual process, or triggered by a build? I still see the old version: `20220117.1642`. Maybe I am misunderstanding something; I have never actually published a package. No rush, by the way, I just wanted to make sure you hadn't skipped a step that you had meant to do since you said it was out there now (I do see it on `master`).

**Comment by awth13** [comment]
@Kazark, MELPA rebuilds all packages in it automatically every X amount of time. The MELPA website currently says "Next build: unknown", so I assume that the new build that will have the latest `org-appear` changes is in the process. The build takes quite a bit of time since there are many packages, one or two hours, I think.

**Comment by Kazark** [comment]
Got it! Thanks for the education!
