### ISSUE TITLE
Error in post-command-hook (org-appear--post-cmd): (void-variable elem-end)

### ISSUE THREAD

**Issue by fwt11** [awth13/org-appear#41]
Maybe this is not the problem of org-appear.
After I upgraded my OS from debian 10 to debian 11, org-appear stop working, with this error

`Error in post-command-hook (org-appear--post-cmd): (void-variable elem-end)`
Run emacs with `--debug-init` gives no more information. 

Please help me!

**Comment by awth13** [comment]
Hi! Thank you for posting the issue!

Would you mind giving some more information about your setup? In particular, your Emacs and Org version and, if you have any complex Org configuration, the parts of code related to Org from your init.el.

**Comment by fwt11** [comment]
I'm sorry, it's not the problem of org-appear.
I use the purcell configuration [https://github.com/purcell/emacs.d](https://github.com/purcell/emacs.d). Org-appear works if I don't use that configuration.
