### ISSUE TITLE
README.org is a bit misleading

### ISSUE THREAD

**Issue by hpgisler** [awth13/org-appear#45]
### The README states:

The manual option is useful for, e.g., integrating org-appear with evil-mode. Below is an example configuration for toggling elements in Insert mode only.

```
(setq org-appear-trigger 'manual)
(add-hook 'evil-insert-state-entry-hook #'org-appear-manual-start nil t)
(add-hook 'evil-insert-state-exit-hook #'org-appear-manual-stop nil t)
```
### HOWEVER:

It would be good to additionally note, that this hook definition is buffer local, i.e. `add-hook` *needs* executed for each opened org buffer.

E.g. if using use-package, this would look as following:

```
(use-package org-appear
	...
	:hook (org-mode . (lambda ()
					(org-appear-mode t)
					(add-hook 'evil-insert-state-entry-hook #'org-appear-manual-start nil t)
					(add-hook 'evil-insert-state-exit-hook #'org-appear-manual-stop nil t)))
 	...
```

**Comment by awth13** [comment]
Thank you for pointing this out. You are absolutely right and I [clarified the README accordingly](https://github.com/awth13/org-appear/commit/8dd1e564153d8007ebc4bb4e14250bde84e26a34).
