### ISSUE TITLE
bug-reference-mode links expansion

### ISSUE THREAD

**Issue by agzam** [awth13/org-appear#49]
Bug-reference-mode uses `link` face, and regular org-mode links and bug-reference-links are not easily distinguishable [when used in Org-mode documents]. It would be great if org-appear could "expand" bug-reference links, revealing the overlay with the full link.

This is probably debatable since bug-reference-mode bears little relation with either Org-mode or org-appear. Still, it would be a useful feature.

**Comment by awth13** [comment]
Hi! This is an interesting suggestion. 

I don't use `bug-reference-mode` but, as I understand from looking at its code, it is meant to be run in `prog-mode` buffers. This probably means that the `org-element` API, which we use to identify elements and which works only in Org mode, will not be able to tell us which element is under our cursor.

We might use `bug-reference-bug-regexp` to find the elements under cursor. This is, however, currently not supported by `org-appear` and I think it is beyond the scope of `org-appear` even, seeing that it is a package tailored for Org mode.

**Comment by agzam** [comment]
Yes, I agree with you, this feature reasonably feels out of scope of `org-appear` project. I just wanted to share my thoughts anyway. Maybe someone (perhaps even myself) would find some time to mess around with it. 
Hope someone finds this issue and posts an update here when that happens.
Closing this for now, since it's not an actionable item.
