### ISSUE TITLE
Stop working when cursor is on a link if `org-fold-core-style` is set to 'overlays, can anyone else confirm? 

### ISSUE THREAD

**Issue by zbelial** [awth13/org-appear#53]
First, thanks for this great package. 

I'm using orgmode 9.6.6 with Emacs 29.1 on Linux. I set `org-fold-core-style` to 'overlays to solve the problem that `org-cycle` does not work sometimes. 

After changing `org-fold-core-style` to 'test-properties (the default value), org-appear works as expected again.

**Comment by walseb** [comment]
I'm also on org 9.6.6 and have `org-fold-core-style` set to `'overlay`. Org-appear works for me, although there are freezes sometimes that I believe to be unrelated to this package. I'm running Emacs `30.0.50`.

**Comment by zbelial** [comment]
Hi @walseb , thanks. 

I have had no luck.  I can reproduce the problem with `emacs -Q`, the following was how I did:
1. emacs -Q
2. eval the config:
```elisp
(add-to-list 'load-path "/path/to/org-appear")

(setq org-fold-core-style 'overlays)

(require 'org)
(require 'org-appear)

(add-hook 'org-mode-hook #'org-appear-mode)

(setq org-appear-trigger 'always)
(setq org-appear-autosubmarkers t)
(setq org-appear-autoentities t)
(setq org-appear-autolinks t)
```
3. Open an org file with links, org-appear does not work when the cursor is on links


`org-fold-core-style` must be set before loading org.  You set it before or after loading org?  Thanks.

**Comment by walseb** [comment]
Hello!

Yes I set it long before org loads, in my early-init.el. However, I don't use org-appear with links, only things like bold, etc. Maybe this is only an issue with links.

**Comment by psionic-k** [comment]
Also was using `(setq org-fold-core-style 'overlays)`.  Turned if off, links work.

**Comment by gw-lucas** [comment]
Interestingly enough, I now have the exact same problem, but the other way around. In Emacs 29.3, with Org 9.6.15.

```lisp
(add-to-list 'load-path "/path/to/org-appear")

(setq org-fold-core-style 'text-properties)

(require 'org)
(require 'org-appear)

(add-hook 'org-mode-hook #'org-appear-mode)

(setq org-appear-trigger 'always)
(setq org-appear-autosubmarkers t)
(setq org-appear-autoentities t)
(setq org-appear-autolinks t)
```

Since `text-properties` is the default value, links were not revealed at first. When I switched to `overlays` after seeing this issue, org-appear started working on links.

**Comment by kvineet** [comment]
I am running emacs `29.3` with org version `9.8`. `org-fold-core-style` is set to `'overlays`

Links are not working for me post [org-fold support were added to org-appear](https://github.com/awth13/org-appear/commit/60ba267c5da336e75e603f8c7ab3f44e6f4e4dac)
If I pin to commit `8dd1e564153d8007ebc4bb4e14250bde84e26a34`, links work. also no issues observed with org-fold.

**Comment by awth13** [comment]
Hey everyone, I'm so sorry it took me so long to respond to this!

It should be fixed now but note that, for Org versions above 9.7, using the [org-9.7-fixes](https://github.com/awth13/org-appear/tree/org-9.7-fixes) branch is recommended. This is all because of huge revamps in `org-fold` and `org-element` over the last 2 years.

Please reopen if there are similar issues after the fix.
