### ISSUE TITLE
org-appear will change the appearance of the cite links of org-ref

### ISSUE THREAD

**Issue by panmengguan** [awth13/org-appear#7]
Org-ref uses `cite:xxxx` as its cite links, however, when I enable the org-appear module, these links will show to be `te:xxxx`, when I move the cursor to the links, it will show to be normal as `cite:xxxx`.

**Comment by awth13** [comment]
Thank you for taking the time to open an issue! This behaviour is now [fixed](https://github.com/awth13/org-appear/commit/19ea96e6e2ce01b8583b25a6e5579f1be207a119) -- `org-appear` will ignore `org-ref` cite links.
