### ISSUE TITLE
Submit to MELPA?

### ISSUE THREAD

**Issue by D4N** [awth13/org-appear#8]
Hi, this package is pretty cool and I think it would benefit from being available in MELPA. Would you be willing to submit it? Or would you not be opposed to someone else submitting it for you?

**Comment by awth13** [comment]
Hey, @D4N! 

I am sorry for the delayed reply. I definitely don't oppose `org-appear` being available in MELPA. In fact, I should've done it a long time ago.

I will work on it this weekend and will let you know once it's done!

**Comment by D4N** [comment]
Thanks a lot!

**Comment by awth13** [comment]
The package is now in MELPA and I am closing this issue.

Let me know if you have any other suggestions!

**Comment by D4N** [comment]
Thanks a lot!

**Comment by japhir** [comment]
Hey thanks for putting it on melpa! Could you change the installation instructions in the README to reflect this? :)

here's my current `use-package` config (with `(setq use-package-always-ensure t)`)

```elisp
  (use-package org-appear
    ;; :straight (org-appear :type git :host github :repo "awth13/org-appear")
    :hook (org-mode . org-appear-mode)
    :config
    (setq org-appear-autolinks t
          org-appear-autosubmarkers t))
```

**Comment by D4N** [comment]
Ilja Kocken ***@***.***> writes:

> Hey thanks for putting it on melpa! Could you change the installation instructions in the README to reflect this? :)
>
> here's my current `use-package` config (with `(setq use-package-always-ensure t)`)
>
> ```elisp
>   (use-package org-appear
>     ;; :straight (org-appear :type git :host github :repo "awth13/org-appear")
>     :hook (org-mode . org-appear-mode)
>     :config
>     (setq org-appear-autolinks t
>           org-appear-autosubmarkers t))
> ```

This is my config using use-package as well:

```
(use-package org-appear-mode
  :ensure org-appear
  :hook org-mode
  :custom
  (org-appear-autoemphasis t)
  (org-appear-autolinks t)
  (org-appear-autosubmarkers t))
```

**Comment by awth13** [comment]
Hey, @japhir!

Could you clarify your proposal? The README does mention MELPA and I didn't want to give specific instructions because people may or may not use `use-package`.

**Comment by japhir** [comment]
Hey, sorry, I guess I missed it because my brain just skipped straight to the code example, which uses straight ;-).

**Comment by awth13** [comment]
Oh, I see what you mean now, @japhir. The `straight` thing does grab your attention, even though it _is_ in the Manual Installation section. I'll think about organising the README better -- I really don't want to give examples for all package managers on Earth though. If you have any suggestions, let me know. Thank you!

**Comment by japhir** [comment]
I think it's fine, I just had a brainfart. Probably also because I remembered that the last time I looked at this package it was not on MELPA yet ;-).
